### PR TITLE
Add patt utils

### PR DESCRIPTION
**Pull request by scottnath**
@sergesemashko @beynya 

setting up importer to use utilities repo

### CODE REVIEW

**Comment by scottnath** [comment]
@sergesemashko @beynya

either of you have time to check this out today?

thanks,
scott

**Comment by beynya** [comment]
@scottnath i'll check

**Comment by scottnath** [comment]
@beynya any update?

**Comment by beynya** [comment]
@scottnath sorry, just a moment

**Comment by beynya** [comment]
:+1: 
looks good

**Pull request merged**
